xsd2php:
    namespaces:
        'http://www.orienteering.org/datastandard/3.0': 'IofXmlPhp\Model'
    destinations_php:
        'IofXmlPhp\Model': './src/Model'
    destinations_jms:
        'IofXmlPhp\Model': './src/Metadata'
    configs_jms:
        xml_cdata: false
